spring:
  main:
    banner-mode: off
  application:
    name: sample-java-spring
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/example
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

logging:
  level:
    com:
      sample: DEBUG
  file:
    path: logs

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always